image: Visual Studio 2019

branches:
  only:
    - master

configuration: Release
platform: Any CPU

before_build:
- cmd: nuget restore

dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build:
  verbosity: minimal

test:
  assemblies:
    - '**\*Test.dll'

artifacts:
- path: nugets\**\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: jUwBx2bcWtQ1/dBA9rYvLAFv7br1ADIaDTJKe0VnsWOgp85CWCa6SYFahIY+Gzvc
  skip_symbols: true
